robobo.module.0=com.mytechia.robobo.framework.remote_control.remotemodule.RemoteControlModule
robobo.module.1=com.mytechia.robobo.framework.remotecontrol.ws.WebsocketSecureRemoteControlModule
robobo.module.2=com.mytechia.robobo.framework.remotecontrol.robobo_discovery.RoboboDiscoveryModule
robobo.module.3=com.mytechia.robobo.framework.remotecontrol.remote_mdns.RemoteMDNSModule
